# Generated by Django 6.0.2 on 2026-03-11 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulist',
            old_name='is_child_sub_menu',
            new_name='deleted',
        ),
        migrations.AddField(
            model_name='menulist',
            name='is_sub_child_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='menu_icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='menu_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='menu_url',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='parent_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
