# Generated by Django 6.0.2 on 2026-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_is_child_sub_menu_menulist_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulist',
            old_name='is_sub_child_menu',
            new_name='is_child_sub_menu',
        ),
        migrations.AlterField(
            model_name='menulist',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='menu_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='menu_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='menu_url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
