# Generated by Django 6.0.2 on 2026-03-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_productmaincategory_prductsubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulist',
            old_name='is_child_sub_menu',
            new_name='is_sub_child_menu',
        ),
    ]
