# Generated by Django 6.0.2 on 2026-02-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='unique_email_active'),
        ),
    ]
